name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite
  workflow_dispatch: # Permite executar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        run: |
          STATS_URL="https://github-readme-stats.vercel.app/api?username=jandrey&show_icons=true&theme=gruvbox&include_all_commits=true&count_private=true"
          sed -i "s|<STATS_URL>|$STATS_URL|g" README.md

      - name: Commit and push if README changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update GitHub Stats"
            git push
          fi
